# Generated by Django 3.1 on 2020-08-18 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(default=datetime.date(2008, 1, 1))),
                ('total', models.IntegerField()),
            ],
            options={
                'ordering': ['-total'],
            },
        ),
    ]
