# Generated by Django 3.1 on 2020-08-19 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(400)]),
        ),
    ]
